import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Covid Tracker',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/images/favicon.png" />
            </head>
            <body className={inter.className}>
                <main className="py-[110px] h-screen flex flex-col justify-center items-center gap-3">
                    {children}
                </main>
            </body>
        </html>
    );
}
